# Generated by Django 5.1.6 on 2025-03-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0003_review_book'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'book')},
        ),
    ]
